In [6]:
import pandas as pd

In [7]:
#dftexto = pd.read_csv("datasets/ds_texto.csv")
dftexto = pd.read_csv("datasets2/ds_texto.csv")
dftexto.head()

,id,rotulo,MAIUSCULAS,EXCLAMA,ASPAS,POL_ABSOLUTO,funct,pronoun,ppron,i,...,negate,verb,adj,interrog,affect,posemo,negemo,anx,anger,sad
0,53,FALSO,0.155062,0.0,0.0,0.500,0.597229,0.482377,0.292642,0.210033,...,0.088629,0.344285,0.229097,0.091416,0.438605,0.125418,0.365504,0.249721,0.000000,0.0
1,1136,VERDADE,0.032086,0.0,0.0,0.250,0.391333,0.266170,0.173010,0.000000,...,0.183391,0.407083,0.079008,0.283737,0.302521,0.129758,0.226891,0.000000,0.153114,0.0
2,695,FALSO,0.727273,0.0,0.0,0.500,0.291783,0.282805,0.245098,0.000000,...,0.000000,0.144175,0.447712,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0
3,3312,VERDADE,0.069199,0.0,0.0,0.625,0.510839,0.251148,0.139925,0.000000,...,0.000000,0.274363,0.085199,0.101990,0.326226,0.139925,0.244670,0.000000,0.000000,0.0
4,1314,VERDADE,0.000000,0.0,0.0,0.500,0.505184,0.248368,0.138376,0.000000,...,0.000000,0.271326,0.084256,0.403444,0.080654,0.138376,0.000000,0.000000,0.000000,0.0

In [8]:
#dfcaption = pd.read_csv("datasets/ds_caption_pt.csv")
#dfcaption = pd.read_csv("datasets/ds_caption.csv")
dfcaption = pd.read_csv("datasets2/ds_caption.csv")
#dfcaption = pd.read_csv("datasets2/ds_caption_em.csv")
dfcaption.head()

,id,rotulo,MAIUSCULAS,EXCLAMA,ASPAS,POL_ABSOLUTO,pronoun,ppron,i,we,...,negate,verb,adj,interrog,affect,posemo,negemo,anx,anger,sad
0,53,FALSO,0.0,0.0,0.0,0.75,0.000000,0.0,0.0,0.0,...,0.0,0.108815,0.185950,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
1,1136,VERDADE,0.0,0.0,0.0,0.90,0.506250,0.0,0.0,0.0,...,0.0,0.548611,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
2,695,FALSO,0.0,0.0,0.0,0.75,0.534066,0.0,0.0,0.0,...,0.0,0.000000,0.000000,0.0,0.307692,0.307692,0.0,0.0,0.0,0.0
3,3312,VERDADE,0.0,0.0,0.0,0.85,0.000000,0.0,0.0,0.0,...,0.0,0.403061,0.612245,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
4,1314,VERDADE,0.0,0.0,0.0,0.45,0.162000,0.0,0.0,0.0,...,0.0,0.000000,0.150000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0

In [9]:
df = pd.merge(dftexto, dfcaption,  left_on='id', right_on='id')
df.head()

,id,rotulo_x,MAIUSCULAS_x,EXCLAMA_x,ASPAS_x,POL_ABSOLUTO_x,funct,pronoun_x,ppron_x,i_x,...,negate_y,verb_y,adj_y,interrog_y,affect_y,posemo_y,negemo_y,anx_y,anger_y,sad_y
0,53,FALSO,0.155062,0.0,0.0,0.500,0.597229,0.482377,0.292642,0.210033,...,0.0,0.108815,0.185950,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
1,1136,VERDADE,0.032086,0.0,0.0,0.250,0.391333,0.266170,0.173010,0.000000,...,0.0,0.548611,0.000000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
2,695,FALSO,0.727273,0.0,0.0,0.500,0.291783,0.282805,0.245098,0.000000,...,0.0,0.000000,0.000000,0.0,0.307692,0.307692,0.0,0.0,0.0,0.0
3,3312,VERDADE,0.069199,0.0,0.0,0.625,0.510839,0.251148,0.139925,0.000000,...,0.0,0.403061,0.612245,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0
4,1314,VERDADE,0.000000,0.0,0.0,0.500,0.505184,0.248368,0.138376,0.000000,...,0.0,0.000000,0.150000,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0

In [10]:
df['rotulo'] = df['rotulo_x']
df = df.drop('rotulo_x',axis=1) 
df = df.drop('rotulo_y',axis=1) 

#for (index, row) in df.iterrows():
#    df.at[index, "rotulo"] = 1 if row["rotulo_x"] == "VERDADEIRO" else 0
#df = df.drop('rotulo_x',axis=1) 
    
#df.to_csv('datasets/ds_full.csv', index=False) 
df.to_csv('datasets2/ds_full.csv', index=False) 
#df.to_csv('datasets2/ds_full_em.csv', index=False)